---
- name: Déployer WordPress
  hosts: all
  become: yes

  vars:
    mariadb_root_password: "examplerootPW"
    wordpress_db_password: "examplePW"
    wordpress_db_name: "wordpress"
    wordpress_db_user: "example"
    wordpress_db_host: "localhost"

  roles:
    - role: common
    - role: mariadb_server
    - role: wordpress
